
UOF_VN =  "centrum" # Unit Of Federation Variable Name ( assumed to be categorical )
FEDERATION_MECHANISM_LOCAL_MODELS_ONLY = "local-models-only" # center-local models
FEDERATION_MECHANISM_UPDATE_SHARING = "model-update-transmission" # FedAvg
FEDERATION_MECHANISM_UPDATE_SHARING_LIST = "model-update-transmission-list" # when one FedAvg model is not enough
FEDERATION_MECHANISM_ENSEMBLE_OF_MODELS = "ensemble-of-models" # mean ensemble
FEDERATION_MECHANISM_ENSEMBLE_OF_MODELS_WITH_LR_FIT_ON_PREDICTIONS = "lr-from-local-models" # stacked ensemble

NA_PLACEHOLDER = 999999999 # only used in pre-processing.

# used both in LASSO and in summarizing results
POSSIBLE_VAR_CATEGORIES <<- list("leeftijd",
                                 "geslacht1",
                                 "kreatinine_gehalte",
                                 c("diabetesDM_y",
                                   sprintf("diabetes%s", NA_PLACEHOLDER) ),
                                 "LVEF",
                                 "PA_druk",
                                 c("chr_longziekte1",
                                   sprintf("chr_longziekte%s", NA_PLACEHOLDER) ),
                                 c("art_vaatpathologie1",
                                   sprintf("art_vaatpathologie%s", NA_PLACEHOLDER) ),
                                 c("neuro_disfunctie1",
                                   sprintf("neuro_disfunctie%s", NA_PLACEHOLDER) ),
                                 c("cardiochir_eerder1",
                                   sprintf("cardiochir_eerder%s", NA_PLACEHOLDER) ),
                                 c("endocarditis1",
                                   sprintf("endocarditis%s", NA_PLACEHOLDER) ),
                                 c("krit_preop_toestand1",
                                   sprintf("krit_preop_toestand%s", NA_PLACEHOLDER) ),
                                 c("instabiele_AP1",
                                   sprintf("instabiele_AP%s", NA_PLACEHOLDER) ),
                                 c("recent_MI1",
                                   sprintf("recent_MI%s", NA_PLACEHOLDER) ),
                                 c("thorac_aortachir1",
                                   sprintf("thorac_aortachir%s", NA_PLACEHOLDER) ),
                                 c("postinfarct_VSR1",
                                   sprintf("postinfarct_VSR%s", NA_PLACEHOLDER) ),
                                 c("dialyse1",
                                   sprintf("dialyse%s", NA_PLACEHOLDER) ),
                                 c("slechte_mobiliteit1",
                                   sprintf("slechte_mobiliteit%s", NA_PLACEHOLDER) ),
                                 c("NYHA2",
                                   "NYHA3",
                                   "NYHA4",
                                   sprintf("NYHA%s", NA_PLACEHOLDER) ),
                                 c("CCS_IV1",
                                   sprintf("CCS_IV%s", NA_PLACEHOLDER) ),
                                 c("urgentieurgent",
                                   "urgentieemergency",
                                   sprintf("urgentie%s", NA_PLACEHOLDER) ),
                                 c("interv_gewichttwo_operations",
                                   sprintf("interv_gewicht%s", NA_PLACEHOLDER) ),
                                 c("CVA_eerder1",
                                   sprintf("CVA_eerder%s", NA_PLACEHOLDER) ),
                                 c("aklepchir_eerder1",
                                   sprintf("aklepchir_eerder%s", NA_PLACEHOLDER) ),
                                 c("PM_eerder1",
                                   sprintf("PM_eerder%s", NA_PLACEHOLDER) ),
                                 c("narcose1",
                                   sprintf("narcose%s", NA_PLACEHOLDER) ),
                                 c("TAVI_toegangtransfemoral",
                                   "TAVI_toegangsubclavian",
                                   "TAVI_toegangtransapical",
                                   "TAVI_toegangdirect_aortic",
                                   sprintf("TAVI_toegang%s", NA_PLACEHOLDER) ),
                                 c("TAVI_predilatatie1",
                                   sprintf("TAVI_predilatatie%s", NA_PLACEHOLDER) ),
                                 c("TAVI_postdilatatie1",
                                   sprintf("TAVI_postdilatatie%s", NA_PLACEHOLDER) ),
                                 c("CVA_restletsel1",
                                   sprintf("CVA_restletsel%s", NA_PLACEHOLDER) ),
                                 c("re_aklep1",
                                   sprintf("re_aklep%s", NA_PLACEHOLDER) ),
                                 "eGFR",
                                 "bmi",
                                 "bsa")

# because we want NYHA_cat1/2/3/4 (and other categoricals) to all be considered as a single variable.
mapping_vars_to_var_categories <<- list(leeftijd = c( "leeftijd" ),
                                        geslacht = c( "geslacht1" ),
                                        kreatinine_gehalte = c( "kreatinine_gehalte" ),
                                        diabetes = c( "diabetesDM_y", sprintf("diabetes%s", NA_PLACEHOLDER) ),
                                        LVEF = c( "LVEF" ),
                                        PA_druk = c( "PA_druk" ),
                                        chr_longziekte = c( "chr_longziekte1", sprintf("chr_longziekte%s", NA_PLACEHOLDER) ),
                                        art_vaatpathologie = c( "art_vaatpathologie1", sprintf("art_vaatpathologie%s", NA_PLACEHOLDER) ),
                                        neuro_disfunctie = c( "neuro_disfunctie1", sprintf("neuro_disfunctie%s", NA_PLACEHOLDER) ),
                                        cardiochir_eerder = c( "cardiochir_eerder1", sprintf("cardiochir_eerder%s", NA_PLACEHOLDER) ),
                                        endocarditis1 = c( "endocarditis1", sprintf("endocarditis%s", NA_PLACEHOLDER) ),
                                        krit_preop_toestand = c( "krit_preop_toestand1", sprintf("krit_preop_toestand%s", NA_PLACEHOLDER) ),
                                        instabiele_AP = c( "instabiele_AP1", sprintf("instabiele_AP%s", NA_PLACEHOLDER) ),
                                        recent_MI = c( "recent_MI1", sprintf("recent_MI%s", NA_PLACEHOLDER) ),
                                        thorac_aortachir = c( "thorac_aortachir1", sprintf("thorac_aortachir%s", NA_PLACEHOLDER) ),
                                        postinfarct_VSR = c( "postinfarct_VSR1", sprintf("postinfarct_VSR%s", NA_PLACEHOLDER) ),
                                        dialyse = c( "dialyse1", sprintf("dialyse%s", NA_PLACEHOLDER) ),
                                        slechte_mobiliteit = c( "slechte_mobiliteit1", sprintf("slechte_mobiliteit%s", NA_PLACEHOLDER) ),
                                        NYHA = c( "NYHA2", "NYHA3", "NYHA4", sprintf("NYHA%s", NA_PLACEHOLDER) ),
                                        CCS_IV = c( "CCS_IV1", sprintf("CCS_IV%s", NA_PLACEHOLDER) ),
                                        urgentie = c( "urgentieurgent", "urgentieemergency", sprintf("urgentie%s", NA_PLACEHOLDER) ),
                                        interv_gewicht = c( "interv_gewichttwo_operations", sprintf("interv_gewicht%s", NA_PLACEHOLDER) ),
                                        CVA_eerder = c( "CVA_eerder1", sprintf("CVA_eerder%s", NA_PLACEHOLDER) ),
                                        aklepchir_eerder = c( "aklepchir_eerder1", sprintf("aklepchir_eerder%s", NA_PLACEHOLDER) ),
                                        PM_eerder = c( "PM_eerder1", sprintf("PM_eerder%s", NA_PLACEHOLDER) ),
                                        narcose = c( "narcose1", sprintf("narcose%s", NA_PLACEHOLDER) ),
                                        TAVI_toegang = c( "TAVI_toegangtransfemoral", "TAVI_toegangsubclavian", "TAVI_toegangtransapical", "TAVI_toegangdirect_aortic", sprintf("TAVI_toegang%s", NA_PLACEHOLDER) ),
                                        TAVI_predilatatie = c( "TAVI_predilatatie1", sprintf("TAVI_predilatatie%s", NA_PLACEHOLDER) ),
                                        TAVI_postdilatatie = c( "TAVI_postdilatatie1", sprintf("TAVI_postdilatatie%s", NA_PLACEHOLDER) ),
                                        CVA_restletsel = c( "CVA_restletsel1", sprintf("CVA_restletsel%s", NA_PLACEHOLDER) ),
                                        re_aklep = c( "re_aklep1", sprintf("re_aklep%s", NA_PLACEHOLDER) ),
                                        eGFR = c( "eGFR" ),
                                        bmi = c( "bmi" ),
                                        bsa = c( "bsa" ) )